// Roza FM Suite — Sample Data
// All registers extracted & preserved from the original DD.html reference file.
// Each register has columns + sample records so the app feels alive on first launch.

import type { ColumnDef } from './types';

export interface RegisterSeed {
  code: string;
  name: string;
  icon: string;
  category: import('./types').RegisterCategory;
  color: string;
  description?: string;
  columns: ColumnDef[];
  records: Record<string, any>[];
}

// helper to keep column definitions terse
const C = (
  name: string,
  type: ColumnDef['type'],
  width = 120,
  options?: string[],
): ColumnDef => ({ name, type, width, options });

export const REGISTER_SEEDS: RegisterSeed[] = [
  // ============================================================
  // OPERATIONS
  // ============================================================
  {
    code: 'meetings',
    name: 'Meeting Minutes',
    icon: 'fa-clipboard-list',
    category: 'operations',
    color: '#3B82F6',
    description: 'Track meeting minutes, decisions, and action items',
    columns: [
      C('Meeting No', 'auto_increment', 80),
      C('Date', 'date', 100),
      C('Location', 'text', 140),
      C('Department', 'department', 120),
      C('Chairperson', 'employee', 130),
      C('Attendees', 'multi_select', 200, ['Ahmed Ali', 'Sara Khan', 'Mohammed Hassan', 'Fatima Al-Rashid', 'John Smith', 'Priya Sharma']),
      C('Agenda', 'long_text', 200),
      C('Discussion', 'long_text', 200),
      C('Decision', 'long_text', 200),
      C('Action', 'long_text', 200),
      C('Responsible Person', 'employee', 130),
      C('Target Date', 'date', 100),
      C('Status', 'status', 100, ['Open', 'In Progress', 'Closed', 'Cancelled']),
      C('Remarks', 'text', 150),
    ],
    records: [
      { Date: '2025-01-15', Location: 'Conference Room A', Department: 'Operations', Chairperson: 'Ahmed Ali', Attendees: ['Ahmed Ali', 'Sara Khan', 'Mohammed Hassan'], Agenda: 'Q1 Maintenance Plan Review', Discussion: 'Reviewed all pending PM schedules and resource allocation for Q1. Team agreed on prioritizing critical equipment.', Decision: 'Approve Q1 PM schedule with 3 additional technicians.', Action: 'Update CMMS with new schedule', 'Responsible Person': 'Sara Khan', 'Target Date': '2025-01-20', Status: 'Closed', Remarks: 'Follow-up in next meeting' },
      { Date: '2025-01-22', Location: 'Meeting Room B', Department: 'Safety', Chairperson: 'Fatima Al-Rashid', Attendees: ['Fatima Al-Rashid', 'Mohammed Hassan', 'John Smith', 'Priya Sharma'], Agenda: 'Fire Safety Compliance Audit', Discussion: 'Annual fire audit findings reviewed. 12 deficiencies identified across Building A and B. Extinguishers in Block C expired.', Decision: 'Immediate replacement of expired extinguishers. Schedule refresher training.', Action: 'Order 24 fire extinguishers', 'Responsible Person': 'Mohammed Hassan', 'Target Date': '2025-02-01', Status: 'In Progress', Remarks: 'Vendor quotation pending' },
      { Date: '2025-02-05', Location: 'Main Boardroom', Department: 'Administration', Chairperson: 'John Smith', Attendees: ['John Smith', 'Ahmed Ali', 'Sara Khan'], Agenda: 'Budget Approval for HVAC Overhaul', Discussion: 'Presented quotation for chiller replacement. Three vendors shortlisted. Estimated cost AED 2.4M.', Decision: 'Approve budget and proceed with Vendor A.', Action: 'Issue PO to Vendor A', 'Responsible Person': 'John Smith', 'Target Date': '2025-02-15', Status: 'Open', Remarks: 'Board approval still needed' },
    ],
  },
  {
    code: 'attendance',
    name: 'Daily Attendance',
    icon: 'fa-calendar-check',
    category: 'operations',
    color: '#3B82F6',
    description: 'Daily employee attendance log',
    columns: [
      C('Record No', 'auto_increment', 70),
      C('Date', 'date', 90),
      C('Employee Name', 'employee', 130),
      C('Department', 'department', 110),
      C('Check In', 'time', 80),
      C('Check Out', 'time', 80),
      C('Total Hours', 'number', 80),
      C('Status', 'status', 90, ['Present', 'Absent', 'Half Day', 'Late', 'On Leave']),
      C('Remarks', 'text', 140),
    ],
    records: [
      { Date: '2025-02-15', 'Employee Name': 'Ahmed Ali', Department: 'Maintenance', 'Check In': '07:45', 'Check Out': '16:30', 'Total Hours': 8.75, Status: 'Present', Remarks: '' },
      { Date: '2025-02-15', 'Employee Name': 'Sara Khan', Department: 'Operations', 'Check In': '08:15', 'Check Out': '16:30', 'Total Hours': 8.25, Status: 'Late', Remarks: 'Traffic delay' },
      { Date: '2025-02-15', 'Employee Name': 'Mohammed Hassan', Department: 'Safety', 'Check In': '07:30', 'Check Out': '16:00', 'Total Hours': 8.5, Status: 'Present', Remarks: '' },
    ],
  },
  {
    code: 'toolbox',
    name: 'Toolbox Talk',
    icon: 'fa-comments',
    category: 'operations',
    color: '#3B82F6',
    description: 'Record toolbox talks and safety briefings',
    columns: [
      C('TT Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Topic', 'text', 180),
      C('Speaker', 'employee', 120),
      C('Attendees', 'multi_select', 200, ['Ahmed Ali', 'Sara Khan', 'Mohammed Hassan', 'Fatima Al-Rashid', 'John Smith', 'Priya Sharma', 'Raj Patel', 'Omar Saeed']),
      C('Location', 'text', 120),
      C('Duration (min)', 'number', 80),
      C('Key Points', 'long_text', 200),
      C('Status', 'status', 90, ['Scheduled', 'Completed', 'Cancelled']),
    ],
    records: [
      { Date: '2025-02-03', Topic: 'Ladder Safety and Fall Prevention', Speaker: 'Fatima Al-Rashid', Attendees: ['Ahmed Ali', 'Mohammed Hassan', 'Raj Patel', 'Omar Saeed'], Location: 'Building A Site Office', 'Duration (min)': 20, 'Key Points': 'Inspect ladder before use. Maintain 3 points of contact. Do not overreach. Secure top and bottom.', Status: 'Completed' },
      { Date: '2025-02-10', Topic: 'Lockout/Tagout Procedures', Speaker: 'Ahmed Ali', Attendees: ['Ahmed Ali', 'Mohammed Hassan', 'Priya Sharma'], Location: 'Main Control Room', 'Duration (min)': 30, 'Key Points': 'Identify all energy sources. Notify affected personnel. Apply locks and tags. Verify zero energy state.', Status: 'Completed' },
      { Date: '2025-02-17', Topic: 'Heat Stress Awareness', Speaker: 'Fatima Al-Rashid', Attendees: ['Mohammed Hassan', 'Raj Patel', 'Omar Saeed', 'Priya Sharma'], Location: 'Site Office', 'Duration (min)': 15, 'Key Points': 'Stay hydrated, take breaks in shade, recognize symptoms of heat exhaustion and heat stroke.', Status: 'Scheduled' },
    ],
  },
  // ============================================================
  // MAINTENANCE
  // ============================================================
  {
    code: 'workorders',
    name: 'Maintenance Work Orders',
    icon: 'fa-wrench',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Track maintenance work orders from open to close',
    columns: [
      C('WO Number', 'auto_increment', 90),
      C('Date', 'date', 90),
      C('Building', 'building', 110),
      C('Site', 'dropdown', 100, ['Main Site', 'North Campus', 'South Campus', 'Offsite']),
      C('Project', 'text', 110),
      C('Floor', 'text', 80),
      C('Area', 'text', 100),
      C('Room', 'text', 90),
      C('Space Code', 'text', 90),
      C('Asset', 'asset', 120),
      C('Fault Description', 'long_text', 180),
      C('Priority', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Assigned To', 'employee', 120),
      C('Status', 'status', 100, ['Open', 'In Progress', 'Completed', 'On Hold', 'Cancelled']),
      C('Completion %', 'percentage', 90),
      C('Estimated Cost', 'currency', 100),
      C('Remarks', 'text', 140),
      C('Before Image', 'image', 100),
      C('After Image', 'image', 100),
      // Workflow status tracking — extended from Open/In Progress/Completed to full lifecycle
      // Replace the existing 'Status' column options by... actually, we can't replace — migration only adds.
      // So we add a new 'WO Stage' column with the full lifecycle:
      C('WO Stage', 'status', 110, ['Open', 'Assigned', 'In Progress', 'On Hold', 'Completion', 'Closed', 'Cancelled']),
      // Time/date tracking for each stage transition
      C('Assigned At', 'datetime', 130),
      C('Started At', 'datetime', 130),
      C('Completed At', 'datetime', 130),
      C('Closed At', 'datetime', 130),
      C('On Hold Reason', 'text', 140),
      // Completion tracking
      C('Completion Notes', 'long_text', 180),
      C('Completion Image', 'image', 100),
      // Assignment tracking
      C('Assigned By', 'employee', 120),
      C('Assignment Notes', 'text', 140),
      // Linked checklist (e.g. "AC Checklist" for an AC maintenance WO)
      C('Linked Checklist', 'text', 140),
      C('Checklist Pass %', 'percentage', 100),
    ],
    records: [
      { Date: '2025-02-10', Building: 'Building A', Asset: 'AHU-01', 'Fault Description': 'Bearing noise and vibration detected during routine inspection. Temperature running 8°C above normal.', Priority: 'High', 'Assigned To': 'Mohammed Hassan', Status: 'In Progress', 'Completion %': 60, 'Estimated Cost': 3500, Remarks: 'Parts ordered from supplier', 'WO Stage': 'In Progress', 'Assigned At': '2025-02-10T08:00', 'Started At': '2025-02-10T09:30', 'Assigned By': 'John Smith', 'Assignment Notes': 'Priority job — customer complaint' },
      { Date: '2025-02-12', Building: 'Building B', Asset: 'Elevator-03', 'Fault Description': 'Door not closing properly. Intermittent sensor fault causing delays.', Priority: 'Critical', 'Assigned To': 'Ahmed Ali', Status: 'Open', 'Completion %': 0, 'Estimated Cost': 1200, Remarks: 'Safety concern - prioritize', 'WO Stage': 'Open' },
      { Date: '2025-02-08', Building: 'Building C', Asset: 'Pump-05', 'Fault Description': 'Seal leakage observed. Minor drip from mechanical seal.', Priority: 'Medium', 'Assigned To': 'Priya Sharma', Status: 'Completed', 'Completion %': 100, 'Estimated Cost': 800, Remarks: 'Seal replaced, tested OK', 'WO Stage': 'Closed', 'Assigned At': '2025-02-08T07:00', 'Started At': '2025-02-08T08:00', 'Completed At': '2025-02-08T11:00', 'Closed At': '2025-02-09T09:00', 'Completion Notes': 'Seal replaced, pump tested under load for 30 minutes. No leakage observed. Recommended next PM in 90 days.', 'Assigned By': 'John Smith' },
      { Date: '2025-02-14', Building: 'Building A', Asset: 'Chiller CH-01', 'Fault Description': 'Refrigerant leak suspected near expansion valve. Pressure dropping overnight.', Priority: 'Critical', 'Assigned To': 'Mohammed Hassan', Status: 'In Progress', 'Completion %': 35, 'Estimated Cost': 5500, Remarks: 'Requires specialist refrigeration tech', 'WO Stage': 'Assigned', 'Assigned At': '2025-02-14T06:30', 'Assigned By': 'John Smith', 'Assignment Notes': 'Emergency — chiller serves data center wing' },
      { Date: '2025-02-15', Building: 'Building D', Asset: 'Generator GEN-02', 'Fault Description': 'Battery voltage low. Auto-start test failed during weekly load bank run.', Priority: 'High', 'Assigned To': 'Ahmed Ali', Status: 'In Progress', 'Completion %': 50, 'Estimated Cost': 2200, Remarks: 'Battery replacement scheduled', 'WO Stage': 'In Progress', 'Assigned At': '2025-02-15T07:00', 'Started At': '2025-02-15T08:15', 'Assigned By': 'John Smith' },
      { Date: '2025-02-16', Building: 'Building B', Asset: 'AHU-03', 'Fault Description': 'Supply air temperature 4°C above setpoint. Filter pressure differential high.', Priority: 'Medium', 'Assigned To': 'Priya Sharma', Status: 'Open', 'Completion %': 0, 'Estimated Cost': 450, Remarks: 'Filter replacement — routine', 'WO Stage': 'Open' },
      { Date: '2025-02-11', Building: 'Building C', Asset: 'Fire Alarm Panel FAP-01', 'Fault Description': 'Zone 7 trouble signal — intermittent. Possible detector fault.', Priority: 'High', 'Assigned To': 'Mohammed Hassan', Status: 'Completed', 'Completion %': 100, 'Estimated Cost': 900, Remarks: 'Detector replaced, zone tested', 'WO Stage': 'Closed', 'Assigned At': '2025-02-11T09:00', 'Started At': '2025-02-11T09:30', 'Completed At': '2025-02-11T13:00', 'Closed At': '2025-02-11T14:30', 'Completion Notes': 'Replaced smoke detector SD-07-12 in Zone 7. All zones tested OK. System back to normal.', 'Assigned By': 'John Smith' },
      { Date: '2025-02-17', Building: 'Building A', Asset: 'Pump-05', 'Fault Description': 'Motor drawing high amperage. Vibration analysis indicates bearing wear.', Priority: 'High', 'Assigned To': 'Ahmed Ali', Status: 'On Hold', 'Completion %': 20, 'Estimated Cost': 3200, Remarks: 'Awaiting bearing delivery from OEM', 'WO Stage': 'On Hold', 'Assigned At': '2025-02-17T07:00', 'Started At': '2025-02-17T08:00', 'On Hold Reason': 'Bearing not in stock — ETA 5 working days from supplier' },
    ],
  },
  {
    code: 'pm',
    name: 'Preventive Maintenance',
    icon: 'fa-clock-rotate-left',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Scheduled preventive maintenance tasks',
    columns: [
      C('PM Number', 'auto_increment', 80),
      C('Equipment', 'equipment', 130),
      C('Location', 'text', 110),
      C('Frequency', 'dropdown', 90, ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Bi-Annual', 'Annual']),
      C('Last Done', 'date', 90),
      C('Next Due', 'date', 90),
      C('Technician', 'employee', 120),
      C('Status', 'status', 100, ['Due', 'Overdue', 'Completed', 'Scheduled']),
      C('WO Stage', 'status', 110, ['Open', 'Assigned', 'In Progress', 'On Hold', 'Completion', 'Closed', 'Cancelled']),
      C('Assigned To', 'employee', 120),
      C('Assigned At', 'datetime', 130),
      C('Started At', 'datetime', 130),
      C('Completed At', 'datetime', 130),
      C('Closed At', 'datetime', 130),
      C('Completion Notes', 'long_text', 180),
      C('Linked Checklist', 'text', 140),
      C('Checklist Pass %', 'percentage', 100),
      C('Before Image', 'image', 100),
      C('After Image', 'image', 100),
    ],
    records: [
      { Equipment: 'Chiller CH-01', Location: 'Plant Room A', Frequency: 'Monthly', 'Last Done': '2025-01-15', 'Next Due': '2025-02-15', Technician: 'Mohammed Hassan', Status: 'Due' },
      { Equipment: 'Generator GEN-02', Location: 'Generator Room', Frequency: 'Weekly', 'Last Done': '2025-02-10', 'Next Due': '2025-02-17', Technician: 'Ahmed Ali', Status: 'Scheduled' },
      { Equipment: 'AHU-03', Location: 'Floor 3 Mechanical Room', Frequency: 'Quarterly', 'Last Done': '2024-12-01', 'Next Due': '2025-03-01', Technician: 'Priya Sharma', Status: 'Scheduled' },
    ],
  },
  {
    code: 'cm',
    name: 'Corrective Maintenance',
    icon: 'fa-hammer',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Record corrective maintenance activities',
    columns: [
      C('CM Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Equipment', 'equipment', 130),
      C('Location', 'text', 110),
      C('Site', 'dropdown', 100, ['Main Site', 'North Campus', 'South Campus', 'Offsite']),
      C('Project', 'text', 110),
      C('Floor', 'text', 80),
      C('Area', 'text', 100),
      C('Room', 'text', 90),
      C('Space Code', 'text', 90),
      C('Fault Description', 'long_text', 180),
      C('Root Cause', 'long_text', 160),
      C('Action Taken', 'long_text', 180),
      C('Technician', 'employee', 120),
      C('Status', 'status', 100, ['Open', 'In Progress', 'Completed', 'Cancelled']),
      C('Completion Date', 'date', 100),
      C('Cost', 'currency', 90),
      C('Before Photo', 'image', 100),
      C('After Photo', 'image', 100),
    ],
    records: [
      { Date: '2025-01-28', Equipment: 'Pump-05', Location: 'Basement Plant Room', 'Fault Description': 'Mechanical seal failure causing water leakage', 'Root Cause': 'Seal degradation due to age and mineral buildup', 'Action Taken': 'Replaced mechanical seal, cleaned impeller, realigned shaft', Technician: 'Priya Sharma', Status: 'Completed', 'Completion Date': '2025-01-29', Cost: 850 },
      { Date: '2025-02-05', Equipment: 'FCU-12', Location: 'Building B Floor 2', 'Fault Description': 'No cooling output, fan running but no air flow', 'Root Cause': 'Frozen coil due to clogged filter restricting airflow', 'Action Taken': 'Replaced filter, defrosted coil, cleaned drain pan', Technician: 'Ahmed Ali', Status: 'Completed', 'Completion Date': '2025-02-05', Cost: 250 },
      { Date: '2025-02-14', Equipment: 'BMS Panel-01', Location: 'Main Control Room', 'Fault Description': 'Intermittent communication loss with field controllers', 'Root Cause': 'Faulty RS-485 converter on bus 3', 'Action Taken': 'Replaced converter, reconfigured bus addressing', Technician: 'Mohammed Hassan', Status: 'In Progress', 'Completion Date': '', Cost: 420 },
    ],
  },
  {
    code: 'gen_log',
    name: 'Generator Logbook',
    icon: 'fa-bolt',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Generator operation log entries',
    columns: [
      C('Log No', 'auto_increment', 70),
      C('Date', 'date', 90),
      C('Time', 'time', 70),
      C('Generator', 'text', 120),
      C('Run Hours', 'number', 70),
      C('Fuel Level %', 'percentage', 80),
      C('Load %', 'percentage', 70),
      C('Coolant Temp (C)', 'number', 90),
      C('Operator', 'employee', 120),
      C('Remarks', 'text', 140),
    ],
    records: [
      { Date: '2025-02-15', Time: '10:00', Generator: 'GEN-01', 'Run Hours': 2456, 'Fuel Level %': 78, 'Load %': 65, 'Coolant Temp (C)': 82, Operator: 'Ahmed Ali', Remarks: 'Monthly load test. All parameters normal.' },
      { Date: '2025-02-15', Time: '10:00', Generator: 'GEN-02', 'Run Hours': 1823, 'Fuel Level %': 85, 'Load %': 0, 'Coolant Temp (C)': 45, Operator: 'Ahmed Ali', Remarks: 'Standby unit. No run this period. Battery voltage OK.' },
      { Date: '2025-02-10', Time: '14:00', Generator: 'GEN-01', 'Run Hours': 2450, 'Fuel Level %': 82, 'Load %': 72, 'Coolant Temp (C)': 84, Operator: 'Raj Patel', Remarks: 'Weekly test run. Black smoke observed at startup, cleared after 2 minutes.' },
    ],
  },
  {
    code: 'chiller_log',
    name: 'Chiller Log Sheet',
    icon: 'fa-snowflake',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Daily chiller operation log',
    columns: [
      C('Log No', 'auto_increment', 70),
      C('Date', 'date', 90),
      C('Time', 'time', 70),
      C('Chiller', 'text', 100),
      C('Supply Temp (C)', 'number', 100),
      C('Return Temp (C)', 'number', 100),
      C('Pressure (bar)', 'number', 90),
      C('Current (A)', 'number', 80),
      C('Operator', 'employee', 120),
      C('Remarks', 'text', 140),
    ],
    records: [
      { Date: '2025-02-15', Time: '08:00', Chiller: 'CH-01', 'Supply Temp (C)': 7.2, 'Return Temp (C)': 12.8, 'Pressure (bar)': 14.2, 'Current (A)': 185, Operator: 'Mohammed Hassan', Remarks: 'Normal operation. COP within spec.' },
      { Date: '2025-02-15', Time: '14:00', Chiller: 'CH-01', 'Supply Temp (C)': 6.8, 'Return Temp (C)': 13.5, 'Pressure (bar)': 14.5, 'Current (A)': 192, Operator: 'Mohammed Hassan', Remarks: 'Peak load period. Slight increase in current draw.' },
      { Date: '2025-02-15', Time: '08:00', Chiller: 'CH-02', 'Supply Temp (C)': 7.5, 'Return Temp (C)': 12.2, 'Pressure (bar)': 13.8, 'Current (A)': 170, Operator: 'Priya Sharma', Remarks: 'Standby chiller on short cycle test. All OK.' },
    ],
  },
  {
    code: 'elec_insp',
    name: 'Electrical Inspection',
    icon: 'fa-plug',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Electrical panel & equipment inspections',
    columns: [
      C('EI Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Location', 'text', 130),
      C('Panel / Equipment', 'text', 140),
      C('Inspector', 'employee', 120),
      C('Voltage (V)', 'number', 80),
      C('Current (A)', 'number', 80),
      C('Insulation (MOhm)', 'number', 100),
      C('Findings', 'long_text', 180),
      C('Status', 'status', 100, ['Pass', 'Fail', 'Conditional Pass', 'Pending']),
    ],
    records: [
      { Date: '2025-02-10', Location: 'Building A Floor 3', 'Panel / Equipment': 'MDB-03F', Inspector: 'Ahmed Ali', 'Voltage (V)': 415, 'Current (A)': 126, 'Insulation (MOhm)': 500, Findings: 'All breakers operational. Labels clear. No signs of overheating. Earth continuity OK.', Status: 'Pass' },
      { Date: '2025-02-12', Location: 'Building B Basement', 'Panel / Equipment': 'SMDB-B-B1', Inspector: 'Raj Patel', 'Voltage (V)': 412, 'Current (A)': 85, 'Insulation (MOhm)': 250, Findings: 'Insulation reading below threshold on Circuit 7. Recommend cable replacement.', Status: 'Conditional Pass' },
      { Date: '2025-02-14', Location: 'Generator Room', 'Panel / Equipment': 'ATS-01', Inspector: 'Ahmed Ali', 'Voltage (V)': 418, 'Current (A)': 0, 'Insulation (MOhm)': 550, Findings: 'ATS function test: changeover time 8 seconds (spec < 10s). All contacts good.', Status: 'Pass' },
    ],
  },
  // ============================================================
  // SAFETY
  // ============================================================
  {
    code: 'safety_insp',
    name: 'Safety Inspection',
    icon: 'fa-shield-halved',
    category: 'safety',
    color: '#EF4444',
    description: 'Safety inspection records',
    columns: [
      C('Inspection No', 'auto_increment', 90),
      C('Date', 'date', 90),
      C('Area', 'text', 120),
      C('Inspector', 'employee', 120),
      C('Type', 'dropdown', 120, ['Routine', 'Surprise', 'Scheduled', 'Follow-up']),
      C('Findings', 'long_text', 200),
      C('Risk Level', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Action Required', 'long_text', 180),
      C('Status', 'status', 100, ['Open', 'In Progress', 'Closed', 'Overdue']),
      C('Due Date', 'date', 90),
    ],
    records: [
      { Date: '2025-02-01', Area: 'Building A - Mechanical Floors', Inspector: 'Fatima Al-Rashid', Type: 'Scheduled', Findings: 'Two fire extinguishers expired. Emergency exit sign on Floor 5 not illuminated. PPE not worn by 2 contractors.', 'Risk Level': 'High', 'Action Required': 'Replace extinguishers, repair exit sign, issue warning to contractor', Status: 'In Progress', 'Due Date': '2025-02-10' },
      { Date: '2025-02-10', Area: 'Construction Zone - Block D', Inspector: 'Mohammed Hassan', Type: 'Surprise', Findings: 'Scaffolding missing guardrails on 2nd level. No safety nets below working area.', 'Risk Level': 'Critical', 'Action Required': 'Stop work immediately. Install guardrails and safety nets before resuming.', Status: 'Closed', 'Due Date': '2025-02-10' },
      { Date: '2025-02-15', Area: 'Parking Basement B2', Inspector: 'Fatima Al-Rashid', Type: 'Routine', Findings: 'Ventilation fan not operational. CO detector showing normal readings. Minor water pooling near drain.', 'Risk Level': 'Medium', 'Action Required': 'Schedule fan repair, clear drain blockage', Status: 'Open', 'Due Date': '2025-02-25' },
    ],
  },
  {
    code: 'risk_assess',
    name: 'Risk Assessment',
    icon: 'fa-triangle-exclamation',
    category: 'safety',
    color: '#EF4444',
    description: 'Risk assessments for hazardous activities',
    columns: [
      C('RA Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Activity', 'text', 160),
      C('Hazard', 'long_text', 180),
      C('Likelihood', 'dropdown', 90, ['Rare', 'Unlikely', 'Possible', 'Likely', 'Almost Certain']),
      C('Severity', 'dropdown', 90, ['Negligible', 'Minor', 'Moderate', 'Major', 'Catastrophic']),
      C('Risk Level', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Control Measures', 'long_text', 200),
      C('Responsible', 'employee', 120),
      C('Status', 'status', 100, ['Draft', 'Under Review', 'Approved', 'Implemented']),
    ],
    records: [
      { Date: '2025-01-20', Activity: 'Working at Height - Roof Maintenance', Hazard: 'Falls from edge, falling tools, slippery surface', Likelihood: 'Possible', Severity: 'Major', 'Risk Level': 'High', 'Control Measures': 'Install guardrails, use harness system, tool lanyards, non-slip footwear, buddy system', Responsible: 'Fatima Al-Rashid', Status: 'Approved' },
      { Date: '2025-02-02', Activity: 'Chemical Handling - Cleaning Agents', Hazard: 'Skin contact, eye splash, inhalation of fumes', Likelihood: 'Likely', Severity: 'Moderate', 'Risk Level': 'High', 'Control Measures': 'PPE (gloves, goggles, mask), SDS available, ventilation, spill kit, trained personnel only', Responsible: 'Mohammed Hassan', Status: 'Implemented' },
      { Date: '2025-02-12', Activity: 'Electrical Panel Maintenance', Hazard: 'Electric shock, arc flash, burns', Likelihood: 'Unlikely', Severity: 'Catastrophic', 'Risk Level': 'High', 'Control Measures': 'LOTO procedure, insulated tools, arc flash PPE, qualified electrician only, permit to work required', Responsible: 'Ahmed Ali', Status: 'Under Review' },
    ],
  },
  {
    code: 'ptw',
    name: 'Permit To Work',
    icon: 'fa-file-signature',
    category: 'safety',
    color: '#EF4444',
    description: 'Permit-to-work issuance and tracking',
    columns: [
      C('PTW Number', 'auto_increment', 90),
      C('Date', 'date', 90),
      C('Work Description', 'long_text', 200),
      C('Location', 'text', 120),
      C('Contractor', 'vendor', 130),
      C('Supervisor', 'employee', 120),
      C('Start Date', 'datetime', 110),
      C('End Date', 'datetime', 110),
      C('Hazard Type', 'multi_select', 150, ['Electrical', 'Height', 'Confined Space', 'Chemical', 'Hot Work', 'Excavation']),
      C('Status', 'status', 100, ['Draft', 'Submitted', 'Approved', 'Active', 'Completed', 'Cancelled']),
      C('Approved By', 'employee', 120),
    ],
    records: [
      { Date: '2025-02-10', 'Work Description': 'Replacement of main distribution board on Floor 3', Location: 'Building A Floor 3 Electrical Room', Contractor: 'Al-Fanar Electrical', Supervisor: 'Ahmed Ali', 'Start Date': '2025-02-15 08:00', 'End Date': '2025-02-15 17:00', 'Hazard Type': ['Electrical'], Status: 'Approved', 'Approved By': 'John Smith' },
      { Date: '2025-02-12', 'Work Description': 'Welding of structural steel supports at roof level', Location: 'Block D Roof', Contractor: 'Gulf Steel Fabrication', Supervisor: 'Mohammed Hassan', 'Start Date': '2025-02-18 07:00', 'End Date': '2025-02-20 17:00', 'Hazard Type': ['Height', 'Hot Work'], Status: 'Submitted', 'Approved By': '' },
      { Date: '2025-02-14', 'Work Description': 'Chemical cleaning of chiller condenser tubes', Location: 'Plant Room A', Contractor: 'CoolTech Services', Supervisor: 'Priya Sharma', 'Start Date': '2025-02-20 06:00', 'End Date': '2025-02-21 18:00', 'Hazard Type': ['Chemical', 'Confined Space'], Status: 'Draft', 'Approved By': '' },
    ],
  },
  {
    code: 'incidents',
    name: 'Incident Report',
    icon: 'fa-burst',
    category: 'safety',
    color: '#EF4444',
    description: 'Incident reporting and tracking',
    columns: [
      C('IR Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Time', 'time', 70),
      C('Location', 'text', 130),
      C('Type', 'dropdown', 120, ['Near Miss', 'Minor Injury', 'Property Damage', 'Environmental', 'Fire', 'Security', 'Other']),
      C('Description', 'long_text', 200),
      C('Severity', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Reported By', 'employee', 120),
      C('Status', 'status', 100, ['Reported', 'Under Investigation', 'Closed', 'Referred']),
      C('Witnesses', 'text', 140),
    ],
    records: [
      { Date: '2025-02-05', Time: '14:30', Location: 'Building A Loading Bay', Type: 'Near Miss', Description: 'Forklift nearly struck a pedestrian due to reversed traffic flow in loading area.', Severity: 'High', 'Reported By': 'Omar Saeed', Status: 'Under Investigation', Witnesses: 'Raj Patel, Security Guard on duty' },
      { Date: '2025-02-11', Time: '09:15', Location: 'Building B Floor 5', Type: 'Minor Injury', Description: 'Technician sustained minor cut on hand while replacing fluorescent tube. Glass broke during removal.', Severity: 'Low', 'Reported By': 'Priya Sharma', Status: 'Closed', Witnesses: 'Ahmed Ali' },
      { Date: '2025-02-14', Time: '22:45', Location: 'Parking B2', Type: 'Property Damage', Description: 'Vehicle backed into concrete pillar causing damage to bumper and pillar surface.', Severity: 'Medium', 'Reported By': 'Security Team', Status: 'Reported', Witnesses: 'CCTV footage available' },
    ],
  },
  {
    code: 'accident',
    name: 'Accident Investigation',
    icon: 'fa-magnifying-glass',
    category: 'safety',
    color: '#EF4444',
    description: 'Accident investigation records',
    columns: [
      C('AI Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Incident Ref', 'text', 100),
      C('Investigator', 'employee', 120),
      C('Root Cause', 'long_text', 200),
      C('Findings', 'long_text', 200),
      C('Recommendations', 'long_text', 200),
      C('Status', 'status', 100, ['In Progress', 'Completed', 'Follow-up Required']),
      C('Due Date', 'date', 90),
    ],
    records: [
      { Date: '2025-02-06', 'Incident Ref': 'IR-2025-002', Investigator: 'Fatima Al-Rashid', 'Root Cause': 'Lack of clear traffic management plan in loading bay. No physical barriers separating pedestrian and vehicle routes.', Findings: 'Forklift operator was following usual route. Pedestrian was taking shortcut. No signage present. Lighting adequate.', Recommendations: 'Install physical barriers, add directional signage, implement pedestrian walkway, brief all drivers and warehouse staff.', Status: 'Completed', 'Due Date': '2025-02-13' },
      { Date: '2025-02-12', 'Incident Ref': 'IR-2025-003', Investigator: 'Ahmed Ali', 'Root Cause': 'Improper handling technique for fluorescent tube removal. No protective gloves worn.', Findings: 'Standard procedure exists but was not followed. Technician was rushing to complete task before shift end.', Recommendations: 'Reissue PPE guidelines, add to toolbox talk agenda, consider LED retrofit to eliminate glass tubes.', Status: 'Follow-up Required', 'Due Date': '2025-02-20' },
    ],
  },
  {
    code: 'fire_equip',
    name: 'Fire Equipment Inspection',
    icon: 'fa-fire-extinguisher',
    category: 'safety',
    color: '#EF4444',
    description: 'Fire equipment inspection log',
    columns: [
      C('FEI Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Equipment Type', 'dropdown', 120, ['Extinguisher', 'Alarm', 'Sprinkler', 'Hose Reel', 'Detector', 'Exit Sign', 'Emergency Light']),
      C('Location', 'text', 140),
      C('Expiry Date', 'date', 90),
      C('Condition', 'dropdown', 100, ['Good', 'Fair', 'Poor', 'Expired', 'Damaged']),
      C('Inspector', 'employee', 120),
      C('Status', 'status', 90, ['Compliant', 'Non-Compliant', 'Action Required']),
    ],
    records: [
      { Date: '2025-02-15', 'Equipment Type': 'Extinguisher', Location: 'Building A Floor 1 - Stairwell A', 'Expiry Date': '2026-03-15', Condition: 'Good', Inspector: 'Fatima Al-Rashid', Status: 'Compliant' },
      { Date: '2025-02-15', 'Equipment Type': 'Extinguisher', Location: 'Building A Floor 5 - Corridor', 'Expiry Date': '2024-12-01', Condition: 'Expired', Inspector: 'Fatima Al-Rashid', Status: 'Non-Compliant' },
      { Date: '2025-02-15', 'Equipment Type': 'Alarm', Location: 'Building B Floor 3 - Manual Call Point', 'Expiry Date': '2027-06-20', Condition: 'Good', Inspector: 'Mohammed Hassan', Status: 'Compliant' },
    ],
  },
  // ============================================================
  // ASSETS & EQUIPMENT
  // ============================================================
  {
    code: 'assets',
    name: 'Asset Register',
    icon: 'fa-building',
    category: 'assets',
    color: '#8B5CF6',
    description: 'Master asset register',
    columns: [
      C('Asset ID', 'auto_increment', 80),
      C('Asset Name', 'text', 160),
      C('Category', 'dropdown', 100, ['HVAC', 'Electrical', 'Plumbing', 'Fire Protection', 'Elevator', 'BMS', 'Structural', 'Furniture', 'IT', 'Vehicle']),
      C('Building', 'building', 100),
      C('Floor', 'text', 60),
      C('Location Detail', 'text', 120),
      C('Purchase Date', 'date', 90),
      C('Value (AED)', 'currency', 110),
      C('Condition', 'dropdown', 90, ['Excellent', 'Good', 'Fair', 'Poor', 'Beyond Repair']),
      C('Status', 'status', 90, ['Active', 'Inactive', 'Under Maintenance', 'Disposed', 'Written Off']),
      C('Product Image', 'image', 100),
      C('Maintenance Frequency', 'dropdown', 110, ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Bi-Annual', 'Annual', 'On Demand', 'None']),
      C('Default Checklist', 'text', 140),
      C('Last Maintenance Date', 'date', 110),
      C('Next Maintenance Due', 'date', 110),
      C('Maintenance Notes', 'long_text', 160),
      C('Warranty Expiry', 'date', 100),
      C('Criticality', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
    ],
    records: [
      { 'Asset Name': 'Chiller CH-01', Category: 'HVAC', Building: 'Building A', Floor: 'B1', 'Location Detail': 'Plant Room A', 'Purchase Date': '2019-06-15', 'Value (AED)': 850000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Monthly', 'Default Checklist': 'MEP Daily Plant Room Inspection', 'Last Maintenance Date': '2025-01-15', 'Next Maintenance Due': '2025-02-15', 'Maintenance Notes': 'Monthly PM — check refrigerant, oil, filters, electrical connections', 'Warranty Expiry': '2024-06-15', Criticality: 'Critical' },
      { 'Asset Name': 'Passenger Elevator EL-01', Category: 'Elevator', Building: 'Building A', Floor: 'All', 'Location Detail': 'Lobby Core', 'Purchase Date': '2018-03-20', 'Value (AED)': 420000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Monthly', 'Default Checklist': 'Elevator Monthly Inspection', 'Last Maintenance Date': '2025-01-20', 'Next Maintenance Due': '2025-02-20', 'Maintenance Notes': 'Monthly lift inspection per OEM schedule', 'Warranty Expiry': '2023-03-20', Criticality: 'Critical' },
      { 'Asset Name': 'Fire Alarm Panel FAP-01', Category: 'Fire Protection', Building: 'Building A', Floor: 'G', 'Location Detail': 'Fire Control Room', 'Purchase Date': '2020-01-10', 'Value (AED)': 185000, Condition: 'Excellent', Status: 'Active', 'Maintenance Frequency': 'Quarterly', 'Default Checklist': 'Fire Protection Quarterly Test', 'Last Maintenance Date': '2024-12-10', 'Next Maintenance Due': '2025-03-10', 'Maintenance Notes': 'Quarterly functional test of all zones', 'Warranty Expiry': '2025-01-10', Criticality: 'Critical' },
      { 'Asset Name': 'Air Handling Unit AHU-01', Category: 'HVAC', Building: 'Building A', Floor: 'Roof', 'Location Detail': 'Roof Plant Room', 'Purchase Date': '2019-07-01', 'Value (AED)': 145000, Condition: 'Fair', Status: 'Under Maintenance', 'Maintenance Frequency': 'Monthly', 'Default Checklist': 'AHU Monthly Inspection', 'Last Maintenance Date': '2025-01-25', 'Next Maintenance Due': '2025-02-25', 'Maintenance Notes': 'Bearing replacement scheduled — vibration detected', 'Warranty Expiry': '2024-07-01', Criticality: 'High' },
      { 'Asset Name': 'Air Handling Unit AHU-03', Category: 'HVAC', Building: 'Building B', Floor: '3', 'Location Detail': 'Floor 3 Mechanical Room', 'Purchase Date': '2020-02-15', 'Value (AED)': 132000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Quarterly', 'Default Checklist': 'AHU Quarterly Inspection', 'Last Maintenance Date': '2024-12-15', 'Next Maintenance Due': '2025-03-15', 'Maintenance Notes': 'Filter replacement due — supply air temp trending high', 'Warranty Expiry': '2025-02-15', Criticality: 'Medium' },
      { 'Asset Name': 'Booster Pump Set BPS-01', Category: 'Plumbing', Building: 'Building A', Floor: 'B2', 'Location Detail': 'Pump Room', 'Purchase Date': '2019-09-10', 'Value (AED)': 95000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Monthly', 'Default Checklist': 'Pump Monthly Inspection', 'Last Maintenance Date': '2025-01-18', 'Next Maintenance Due': '2025-02-18', 'Maintenance Notes': 'Check seals, impeller, motor amperage, pressure gauges', 'Warranty Expiry': '2024-09-10', Criticality: 'High' },
      { 'Asset Name': 'Circulation Pump P-05', Category: 'Plumbing', Building: 'Building C', Floor: 'B1', 'Location Detail': 'Plant Room C', 'Purchase Date': '2018-11-05', 'Value (AED)': 38000, Condition: 'Fair', Status: 'Under Maintenance', 'Maintenance Frequency': 'Quarterly', 'Default Checklist': 'Pump Quarterly Inspection', 'Last Maintenance Date': '2025-01-10', 'Next Maintenance Due': '2025-04-10', 'Maintenance Notes': 'Motor bearing wear detected via vibration analysis — replacement scheduled', 'Warranty Expiry': '2023-11-05', Criticality: 'High' },
      { 'Asset Name': 'Diesel Generator GEN-02', Category: 'Electrical', Building: 'Building D', Floor: 'G', 'Location Detail': 'Generator Room', 'Purchase Date': '2018-09-01', 'Value (AED)': 680000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Weekly', 'Default Checklist': 'Generator Weekly Load Test', 'Last Maintenance Date': '2025-02-10', 'Next Maintenance Due': '2025-02-17', 'Maintenance Notes': 'Weekly load bank test + monthly full service. Battery replacement pending.', 'Warranty Expiry': '2023-09-01', Criticality: 'Critical' },
      { 'Asset Name': 'Transformer TR-01', Category: 'Electrical', Building: 'Building A', Floor: 'B1', 'Location Detail': 'Substation Room', 'Purchase Date': '2017-04-12', 'Value (AED)': 540000, Condition: 'Good', Status: 'Active', 'Maintenance Frequency': 'Annual', 'Default Checklist': 'Transformer Annual Maintenance', 'Last Maintenance Date': '2024-04-15', 'Next Maintenance Due': '2025-04-15', 'Maintenance Notes': 'Annual oil sampling, DG analysis, bushing inspection, tap changer service', 'Warranty Expiry': '2022-04-12', Criticality: 'Critical' },
      { 'Asset Name': 'BMS Controller BMS-01', Category: 'BMS', Building: 'Building A', Floor: 'G', 'Location Detail': 'IT Server Room', 'Purchase Date': '2021-03-01', 'Value (AED)': 220000, Condition: 'Excellent', Status: 'Active', 'Maintenance Frequency': 'Bi-Annual', 'Default Checklist': 'BMS Bi-Annual Calibration', 'Last Maintenance Date': '2024-10-01', 'Next Maintenance Due': '2025-04-01', 'Maintenance Notes': 'Sensor calibration, trend log review, software update', 'Warranty Expiry': '2026-03-01', Criticality: 'Medium' },
    ],
  },
  {
    code: 'equipment',
    name: 'Equipment Register',
    icon: 'fa-gear',
    category: 'assets',
    color: '#8B5CF6',
    description: 'Equipment master register',
    columns: [
      C('Equipment ID', 'auto_increment', 90),
      C('Name', 'text', 150),
      C('Type', 'dropdown', 100, ['Chiller', 'AHU', 'FCU', 'Pump', 'Fan', 'Motor', 'Panel', 'Generator', 'Transformer', 'Compressor']),
      C('Brand', 'text', 90),
      C('Model', 'text', 90),
      C('Serial No', 'text', 120),
      C('Location', 'text', 130),
      C('Installation Date', 'date', 100),
      C('Status', 'status', 90, ['Operational', 'Under Repair', 'Standby', 'Decommissioned']),
    ],
    records: [
      { Name: 'Chiller CH-01', Type: 'Chiller', Brand: 'York', Model: 'YKFLPN45', 'Serial No': 'YK-2019-45872', Location: 'Plant Room A', 'Installation Date': '2019-07-01', Status: 'Operational' },
      { Name: 'AHU-03', Type: 'AHU', Brand: 'Carrier', Model: '39M-070', 'Serial No': 'CR-2020-78431', Location: 'Floor 3 Mech Room', 'Installation Date': '2020-02-15', Status: 'Operational' },
      { Name: 'Generator GEN-02', Type: 'Generator', Brand: 'Caterpillar', Model: 'C18-600', 'Serial No': 'CAT-2018-32156', Location: 'Generator Room', 'Installation Date': '2018-09-01', Status: 'Standby' },
    ],
  },
  {
    code: 'buildings',
    name: 'Building Register',
    icon: 'fa-city',
    category: 'assets',
    color: '#8B5CF6',
    description: 'Building master register',
    columns: [
      C('Building Code', 'auto_increment', 100),
      C('Name', 'text', 160),
      C('Address', 'text', 200),
      C('Floors', 'number', 60),
      C('Area (sqm)', 'number', 90),
      C('Year Built', 'number', 70),
      C('Condition', 'dropdown', 90, ['Excellent', 'Good', 'Fair', 'Poor']),
      C('Status', 'status', 90, ['Active', 'Under Renovation', 'Decommissioned']),
      C('Occupancy %', 'percentage', 90),
      C('Site', 'dropdown', 100, ['Main Site', 'North Campus', 'South Campus']),
      C('Floors', 'number', 80),
      C('Gross Area (sqm)', 'number', 110),
      C('Year Built', 'number', 80),
    ],
    records: [
      { Name: 'Building A - Headquarters', Address: 'Sheikh Zayed Road, Dubai', Floors: 12, 'Area (sqm)': 18500, 'Year Built': 2018, Condition: 'Excellent', Status: 'Active', 'Occupancy %': 95 },
      { Name: 'Building B - Operations', Address: 'Sheikh Zayed Road, Dubai', Floors: 8, 'Area (sqm)': 12000, 'Year Built': 2015, Condition: 'Good', Status: 'Active', 'Occupancy %': 88 },
      { Name: 'Building C - Warehouse', Address: 'Al Quoz Industrial Area', Floors: 2, 'Area (sqm)': 4500, 'Year Built': 2012, Condition: 'Fair', Status: 'Under Renovation', 'Occupancy %': 45 },
    ],
  },
  {
    code: 'calibration',
    name: 'Calibration Register',
    icon: 'fa-ruler-combined',
    category: 'assets',
    color: '#8B5CF6',
    description: 'Equipment calibration records',
    columns: [
      C('Cal ID', 'auto_increment', 70),
      C('Equipment', 'equipment', 140),
      C('Serial No', 'text', 120),
      C('Location', 'text', 120),
      C('Last Calibrated', 'date', 100),
      C('Next Due', 'date', 90),
      C('Standard', 'text', 130),
      C('Status', 'status', 90, ['Calibrated', 'Due', 'Overdue', 'Out of Service']),
    ],
    records: [
      { Equipment: 'Pressure Gauge PG-01', 'Serial No': 'PG-2023-110', Location: 'Plant Room A', 'Last Calibrated': '2025-01-15', 'Next Due': '2025-07-15', Standard: 'ISO 8655', Status: 'Calibrated' },
      { Equipment: 'Multimeter FL-03', 'Serial No': 'FL-2022-445', Location: 'Electrical Workshop', 'Last Calibrated': '2024-11-20', 'Next Due': '2025-02-20', Standard: 'IEC 61010', Status: 'Due' },
      { Equipment: 'Thermocouple TC-07', 'Serial No': 'TC-2024-089', Location: 'Chiller Plant', 'Last Calibrated': '2024-08-10', 'Next Due': '2025-02-10', Standard: 'IEC 60584', Status: 'Overdue' },
    ],
  },
  // ============================================================
  // PROCUREMENT & INVENTORY
  // ============================================================
  {
    code: 'vendors',
    name: 'Vendor Register',
    icon: 'fa-truck-field',
    category: 'procurement',
    color: '#10B981',
    description: 'Vendor master register',
    columns: [
      C('Vendor ID', 'auto_increment', 80),
      C('Company Name', 'text', 180),
      C('Contact Person', 'text', 130),
      C('Phone', 'phone', 120),
      C('Email', 'email', 160),
      C('Category', 'dropdown', 110, ['MEP', 'Cleaning', 'Security', 'IT', 'HVAC', 'Electrical', 'Civil', 'General']),
      C('Rating', 'rating', 80),
      C('Status', 'status', 90, ['Active', 'Inactive', 'Blacklisted', 'Under Review']),
    ],
    records: [
      { 'Company Name': 'CoolTech Services LLC', 'Contact Person': 'Khalid Ibrahim', Phone: '+971-50-123-4567', Email: 'info@cooltech.ae', Category: 'HVAC', Rating: 4, Status: 'Active' },
      { 'Company Name': 'GuardForce International', 'Contact Person': 'Samir Nasser', Phone: '+971-50-234-5678', Email: 'ops@guardforce.ae', Category: 'Security', Rating: 5, Status: 'Active' },
      { 'Company Name': 'Al-Fanar Electrical Co.', 'Contact Person': 'Rashid Ahmad', Phone: '+971-50-345-6789', Email: 'projects@alfanar.ae', Category: 'Electrical', Rating: 3, Status: 'Active' },
    ],
  },
  {
    code: 'contracts',
    name: 'Contract Register',
    icon: 'fa-file-contract',
    category: 'procurement',
    color: '#10B981',
    description: 'Contract register',
    columns: [
      C('Contract No', 'auto_increment', 90),
      C('Title', 'text', 180),
      C('Vendor', 'vendor', 140),
      C('Start Date', 'date', 90),
      C('End Date', 'date', 90),
      C('Value (AED)', 'currency', 110),
      C('Department', 'department', 110),
      C('Status', 'status', 100, ['Active', 'Expired', 'Pending', 'Terminated', 'Under Review']),
      C('Renewal Date', 'date', 90),
    ],
    records: [
      { Title: 'Annual HVAC Maintenance', Vendor: 'CoolTech Services LLC', 'Start Date': '2025-01-01', 'End Date': '2025-12-31', 'Value (AED)': 480000, Department: 'Maintenance', Status: 'Active', 'Renewal Date': '2025-11-01' },
      { Title: 'Security Services', Vendor: 'GuardForce International', 'Start Date': '2024-07-01', 'End Date': '2025-06-30', 'Value (AED)': 720000, Department: 'Administration', Status: 'Active', 'Renewal Date': '2025-05-01' },
      { Title: 'Elevator Maintenance Agreement', Vendor: 'Schindler Middle East', 'Start Date': '2024-04-01', 'End Date': '2025-03-31', 'Value (AED)': 350000, Department: 'Maintenance', Status: 'Under Review', 'Renewal Date': '2025-02-15' },
    ],
  },
  {
    code: 'mat_req',
    name: 'Material Request',
    icon: 'fa-boxes-stacked',
    category: 'procurement',
    color: '#10B981',
    description: 'Material request register',
    columns: [
      C('MR Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Requested By', 'employee', 120),
      C('Department', 'department', 110),
      C('Item Description', 'text', 180),
      C('Quantity', 'number', 70),
      C('Unit', 'dropdown', 60, ['Pcs', 'Kg', 'Mtr', 'Ltr', 'Set', 'Roll', 'Box', 'Bag']),
      C('Urgency', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Status', 'status', 100, ['Draft', 'Submitted', 'Approved', 'Rejected', 'Partial', 'Fulfilled']),
    ],
    records: [
      { Date: '2025-02-10', 'Requested By': 'Mohammed Hassan', Department: 'Maintenance', 'Item Description': 'Mechanical Seal for Pump-05', Quantity: 2, Unit: 'Pcs', Urgency: 'High', Status: 'Approved' },
      { Date: '2025-02-12', 'Requested By': 'Ahmed Ali', Department: 'Maintenance', 'Item Description': 'HEPA Filter 610x610x292', Quantity: 8, Unit: 'Pcs', Urgency: 'Medium', Status: 'Submitted' },
      { Date: '2025-02-14', 'Requested By': 'Fatima Al-Rashid', Department: 'Safety', 'Item Description': 'Fire Extinguisher ABC 9kg', Quantity: 24, Unit: 'Pcs', Urgency: 'Critical', Status: 'Draft' },
    ],
  },
  {
    code: 'pur_req',
    name: 'Purchase Request',
    icon: 'fa-cart-shopping',
    category: 'procurement',
    color: '#10B981',
    description: 'Purchase request register',
    columns: [
      C('PR Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Requested By', 'employee', 120),
      C('Department', 'department', 110),
      C('Description', 'long_text', 200),
      C('Estimated Cost', 'currency', 110),
      C('Priority', 'priority', 90, ['Critical', 'High', 'Medium', 'Low']),
      C('Status', 'status', 110, ['Draft', 'Submitted', 'Approved', 'PO Issued', 'Rejected', 'Cancelled']),
      C('Budget Code', 'text', 100),
    ],
    records: [
      { Date: '2025-02-11', 'Requested By': 'John Smith', Department: 'Administration', Description: 'Replacement of 24 fire extinguishers (ABC 9kg) with certification. Includes delivery and installation at Buildings A, B, C.', 'Estimated Cost': 4800, Priority: 'Critical', Status: 'Approved', 'Budget Code': 'SAF-2025-001' },
      { Date: '2025-02-13', 'Requested By': 'Priya Sharma', Department: 'Maintenance', Description: 'Supply and delivery of 8 HEPA filters 610x610x292mm for AHU units in Building A.', 'Estimated Cost': 6400, Priority: 'Medium', Status: 'Submitted', 'Budget Code': 'MNT-2025-015' },
      { Date: '2025-02-14', 'Requested By': 'Ahmed Ali', Department: 'Maintenance', Description: 'Chiller compressor overhaul kit for York YKFLPN45 including gaskets, bearings, and oil.', 'Estimated Cost': 35000, Priority: 'High', Status: 'Draft', 'Budget Code': 'MNT-2025-016' },
    ],
  },
  {
    code: 'inventory',
    name: 'Inventory Register',
    icon: 'fa-warehouse',
    category: 'procurement',
    color: '#10B981',
    description: 'Inventory items master',
    columns: [
      C('Item Code', 'auto_increment', 80),
      C('Description', 'text', 180),
      C('Category', 'dropdown', 100, ['Electrical', 'Mechanical', 'HVAC', 'Safety', 'Cleaning', 'Office', 'IT', 'Plumbing', 'Fire Protection']),
      C('Unit', 'dropdown', 60, ['Pcs', 'Kg', 'Mtr', 'Ltr', 'Set', 'Roll', 'Box', 'Bag']),
      C('Qty In Stock', 'number', 80),
      C('Min Level', 'number', 70),
      C('Max Level', 'number', 70),
      C('Location', 'text', 110),
      C('Status', 'status', 90, ['In Stock', 'Low Stock', 'Out of Stock', 'On Order', 'Expired']),
    ],
    records: [
      { Description: 'HEPA Filter 610x610x292', Category: 'HVAC', Unit: 'Pcs', 'Qty In Stock': 4, 'Min Level': 8, 'Max Level': 30, Location: 'Store A - Shelf 3', Status: 'Low Stock' },
      { Description: 'Fire Extinguisher ABC 9kg', Category: 'Fire Protection', Unit: 'Pcs', 'Qty In Stock': 6, 'Min Level': 10, 'Max Level': 40, Location: 'Store B - Safety Rack', Status: 'Low Stock' },
      { Description: 'Ball Valve 25mm BSP', Category: 'Plumbing', Unit: 'Pcs', 'Qty In Stock': 25, 'Min Level': 10, 'Max Level': 50, Location: 'Store A - Shelf 7', Status: 'In Stock' },
    ],
  },
  {
    code: 'siv',
    name: 'Store Issue Voucher',
    icon: 'fa-right-from-bracket',
    category: 'procurement',
    color: '#10B981',
    description: 'Store issue voucher register',
    columns: [
      C('SIV Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Issued To', 'employee', 120),
      C('Department', 'department', 110),
      C('Item', 'text', 160),
      C('Quantity', 'number', 70),
      C('Approved By', 'employee', 120),
      C('Status', 'status', 100, ['Draft', 'Approved', 'Issued', 'Returned', 'Cancelled']),
    ],
    records: [
      { Date: '2025-02-10', 'Issued To': 'Priya Sharma', Department: 'Maintenance', Item: 'Mechanical Seal for Pump-05', Quantity: 2, 'Approved By': 'Ahmed Ali', Status: 'Issued' },
      { Date: '2025-02-12', 'Issued To': 'Mohammed Hassan', Department: 'Maintenance', Item: 'Ball Valve 25mm BSP', Quantity: 3, 'Approved By': 'Ahmed Ali', Status: 'Issued' },
      { Date: '2025-02-15', 'Issued To': 'Fatima Al-Rashid', Department: 'Safety', Item: 'Safety Helmet - White', Quantity: 5, 'Approved By': 'John Smith', Status: 'Approved' },
    ],
  },
  // ============================================================
  // HR
  // ============================================================
  {
    code: 'visitors',
    name: 'Visitor Register',
    icon: 'fa-id-card',
    category: 'hr',
    color: '#EC4899',
    description: 'Visitor log',
    columns: [
      C('Record No', 'auto_increment', 70),
      C('Date', 'date', 90),
      C('Visitor Name', 'text', 140),
      C('Company', 'text', 140),
      C('Purpose', 'text', 140),
      C('Host', 'employee', 120),
      C('Department', 'department', 100),
      C('Check In', 'time', 80),
      C('Check Out', 'time', 80),
      C('Badge No', 'text', 70),
    ],
    records: [
      { Date: '2025-02-15', 'Visitor Name': 'Khalid Ibrahim', Company: 'CoolTech Services LLC', Purpose: 'Chiller inspection', Host: 'Mohammed Hassan', Department: 'Maintenance', 'Check In': '09:00', 'Check Out': '11:30', 'Badge No': 'V-0152' },
      { Date: '2025-02-15', 'Visitor Name': 'Layla Mahmoud', Company: 'DEWA', Purpose: 'Meter reading', Host: 'Sara Khan', Department: 'Operations', 'Check In': '10:15', 'Check Out': '10:45', 'Badge No': 'V-0153' },
      { Date: '2025-02-14', 'Visitor Name': 'Tariq Al-Sayed', Company: 'Schindler Middle East', Purpose: 'Elevator annual inspection', Host: 'Ahmed Ali', Department: 'Maintenance', 'Check In': '08:30', 'Check Out': '15:00', 'Badge No': 'V-0151' },
    ],
  },
  {
    code: 'leave',
    name: 'Leave Request',
    icon: 'fa-calendar-minus',
    category: 'hr',
    color: '#EC4899',
    description: 'Employee leave requests',
    columns: [
      C('LR Number', 'auto_increment', 80),
      C('Employee', 'employee', 130),
      C('Department', 'department', 110),
      C('Leave Type', 'dropdown', 110, ['Annual', 'Sick', 'Emergency', 'Maternity', 'Paternity', 'Unpaid', 'Hajj']),
      C('From Date', 'date', 90),
      C('To Date', 'date', 90),
      C('Days', 'number', 60),
      C('Reason', 'text', 160),
      C('Status', 'status', 100, ['Draft', 'Submitted', 'Approved', 'Rejected', 'Cancelled']),
      C('Approved By', 'employee', 120),
    ],
    records: [
      { Employee: 'Sara Khan', Department: 'Operations', 'Leave Type': 'Annual', 'From Date': '2025-02-20', 'To Date': '2025-02-22', Days: 3, Reason: 'Personal travel', Status: 'Approved', 'Approved By': 'John Smith' },
      { Employee: 'Raj Patel', Department: 'Maintenance', 'Leave Type': 'Sick', 'From Date': '2025-02-13', 'To Date': '2025-02-14', Days: 2, Reason: 'Medical appointment and recovery', Status: 'Approved', 'Approved By': 'Ahmed Ali' },
      { Employee: 'Omar Saeed', Department: 'Safety', 'Leave Type': 'Emergency', 'From Date': '2025-02-18', 'To Date': '2025-02-18', Days: 1, Reason: 'Family emergency', Status: 'Submitted', 'Approved By': '' },
    ],
  },
  {
    code: 'training',
    name: 'Training Record',
    icon: 'fa-graduation-cap',
    category: 'hr',
    color: '#EC4899',
    description: 'Employee training records',
    columns: [
      C('TR Number', 'auto_increment', 80),
      C('Employee', 'employee', 130),
      C('Department', 'department', 110),
      C('Course', 'text', 180),
      C('Provider', 'text', 140),
      C('Date', 'date', 90),
      C('Duration (hrs)', 'number', 80),
      C('Certificate', 'dropdown', 90, ['Yes', 'No', 'Pending']),
      C('Status', 'status', 90, ['Completed', 'Scheduled', 'In Progress', 'Cancelled']),
    ],
    records: [
      { Employee: 'Fatima Al-Rashid', Department: 'Safety', Course: 'NEBOSH IGC', Provider: 'British Safety Council', Date: '2025-01-10', 'Duration (hrs)': 80, Certificate: 'Pending', Status: 'Completed' },
      { Employee: 'Ahmed Ali', Department: 'Maintenance', Course: 'HVAC Advanced Troubleshooting', Provider: 'Carrier Training Center', Date: '2025-02-20', 'Duration (hrs)': 16, Certificate: 'No', Status: 'Scheduled' },
      { Employee: 'Mohammed Hassan', Department: 'Safety', Course: 'First Aid at Work', Provider: 'Red Crescent', Date: '2025-01-25', 'Duration (hrs)': 8, Certificate: 'Yes', Status: 'Completed' },
    ],
  },
  // ============================================================
  // PERFORMANCE & QUALITY
  // ============================================================
  {
    code: 'housekeeping',
    name: 'Housekeeping Inspection',
    icon: 'fa-broom',
    category: 'performance',
    color: '#06B6D4',
    description: 'Housekeeping inspection scores',
    columns: [
      C('HI Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Area', 'text', 140),
      C('Inspector', 'employee', 120),
      C('Cleanliness', 'rating', 100),
      C('Safety', 'rating', 80),
      C('Hygiene', 'rating', 80),
      C('Overall Score', 'number', 90),
      C('Remarks', 'text', 160),
      C('Status', 'status', 90, ['Pass', 'Fail', 'Needs Improvement']),
    ],
    records: [
      { Date: '2025-02-15', Area: 'Building A Lobby & Reception', Inspector: 'Sara Khan', Cleanliness: 5, Safety: 5, Hygiene: 5, 'Overall Score': 100, Remarks: 'Excellent condition. All areas spotless.', Status: 'Pass' },
      { Date: '2025-02-15', Area: 'Building B Floor 4 Toilets', Inspector: 'Sara Khan', Cleanliness: 3, Safety: 4, Hygiene: 3, 'Overall Score': 67, Remarks: 'Stain on floor. Soap dispensers not refilled. Needs attention.', Status: 'Needs Improvement' },
      { Date: '2025-02-14', Area: 'Parking B1 & B2', Inspector: 'Omar Saeed', Cleanliness: 4, Safety: 4, Hygiene: 4, 'Overall Score': 80, Remarks: 'Generally clean. Some oil stains in B2. Drainage needs clearing.', Status: 'Pass' },
    ],
  },
  {
    code: 'kpi',
    name: 'Monthly KPI Register',
    icon: 'fa-chart-line',
    category: 'performance',
    color: '#06B6D4',
    description: 'Monthly KPI tracking',
    columns: [
      C('KPI ID', 'auto_increment', 70),
      C('Month', 'date', 90),
      C('Department', 'department', 110),
      C('KPI Name', 'text', 180),
      C('Target', 'number', 70),
      C('Actual', 'number', 70),
      C('Variance', 'number', 70),
      C('Unit', 'text', 60),
      C('Status', 'status', 90, ['On Track', 'At Risk', 'Behind', 'Achieved', 'Exceeded']),
    ],
    records: [
      { Month: '2025-01-01', Department: 'Maintenance', 'KPI Name': 'PM Completion Rate', Target: 95, Actual: 92, Variance: -3, Unit: '%', Status: 'At Risk' },
      { Month: '2025-01-01', Department: 'Safety', 'KPI Name': 'Lost Time Injury Rate', Target: 0, Actual: 0, Variance: 0, Unit: 'Count', Status: 'Achieved' },
      { Month: '2025-01-01', Department: 'Operations', 'KPI Name': 'Energy Consumption per sqm', Target: 45, Actual: 42, Variance: -3, Unit: 'kWh', Status: 'Exceeded' },
    ],
  },
  // ============================================================
  // NEW REGISTERS — Safety & Location Master
  // ============================================================
  {
    code: 'method_stmt',
    name: 'Method Statements',
    icon: 'fa-clipboard-list',
    category: 'safety',
    color: '#EF4444',
    description: 'Method statements for hazardous work activities',
    columns: [
      C('MS Number', 'auto_increment', 80),
      C('Date', 'date', 90),
      C('Title', 'text', 180),
      C('Scope', 'dropdown', 130, ['Marine', 'Soft Services', 'Landscape', 'MEP', 'Civil', 'Security', 'HVAC', 'Electrical', 'Plumbing', 'General']),
      C('Activity', 'long_text', 180),
      C('Reference Standard', 'text', 130),
      C('Responsibility', 'employee', 120),
      C('Reviewed By', 'employee', 120),
      C('Approved By', 'employee', 120),
      C('Status', 'status', 100, ['Draft', 'Under Review', 'Approved', 'Rejected', 'Superseded']),
      C('Revision', 'text', 80),
      C('Document URL', 'url', 140),
    ],
    records: [
      { Date: '2025-01-15', Title: 'Chiller Replacement Method Statement', Scope: 'HVAC', Activity: 'Removal of existing chiller and installation of new unit including electrical and piping connections', 'Reference Standard': 'ASHRAE 15, ASME B31.5', Responsibility: 'Mohammed Hassan', 'Reviewed By': 'John Smith', 'Approved By': 'Ahmed Ali', Status: 'Approved', Revision: 'Rev 02', 'Document URL': '' },
      { Date: '2025-02-01', Title: 'High Pressure Cleaning of Facade', Scope: 'Soft Services', Activity: 'High pressure water cleaning of building facade using suspended access equipment', 'Reference Standard': 'IRATA ICOP, OSHA 1910.140', Responsibility: 'Priya Sharma', 'Reviewed By': 'Fatima Al-Rashid', 'Approved By': 'John Smith', Status: 'Approved', Revision: 'Rev 01', 'Document URL': '' },
      { Date: '2025-02-10', Title: 'Switchgear Inspection Method', Scope: 'Electrical', Activity: 'Preventive inspection and testing of MV switchgear including contact resistance and insulation resistance tests', 'Reference Standard': 'IEC 62271-200, NETA MTS-2017', Responsibility: 'Ahmed Ali', 'Reviewed By': 'Mohammed Hassan', 'Approved By': 'John Smith', Status: 'Under Review', Revision: 'Rev 00', 'Document URL': '' },
    ],
  },
  {
    code: 'checklists',
    name: 'Checklist Templates',
    icon: 'fa-list-check',
    category: 'safety',
    color: '#EF4444',
    description: 'Scope-based checklist templates for inspections',
    columns: [
      C('CL Number', 'auto_increment', 80),
      C('Title', 'text', 180),
      C('Scope', 'dropdown', 130, ['Marine', 'Soft Services', 'Landscape', 'MEP', 'Civil', 'Security', 'Fire Protection', 'HVAC', 'Electrical', 'Plumbing', 'General']),
      C('Category', 'dropdown', 120, ['Pre-Work', 'Inspection', 'Safety', 'Quality', 'Handover', 'Daily', 'Weekly', 'Monthly']),
      C('Total Items', 'number', 80),
      C('Pass Criteria (%)', 'percentage', 100),
      C('Frequency', 'dropdown', 100, ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Annual', 'Per Job']),
      C('Custom Scope', 'text', 120),
      C('Owner', 'employee', 120),
      C('Status', 'status', 100, ['Draft', 'Active', 'Archived']),
    ],
    records: [
      { Title: 'MEP Daily Plant Room Inspection', Scope: 'MEP', Category: 'Daily', 'Total Items': 24, 'Pass Criteria (%)': 90, Frequency: 'Daily', 'Custom Scope': '', Owner: 'Mohammed Hassan', Status: 'Active' },
      { Title: 'Marine Port Facility Pre-Work Checklist', Scope: 'Marine', Category: 'Pre-Work', 'Total Items': 32, 'Pass Criteria (%)': 100, Frequency: 'Per Job', 'Custom Scope': '', Owner: 'Ahmed Ali', Status: 'Active' },
      { Title: 'Soft Services Daily Cleaning Audit', Scope: 'Soft Services', Category: 'Inspection', 'Total Items': 18, 'Pass Criteria (%)': 85, Frequency: 'Daily', 'Custom Scope': '', Owner: 'Priya Sharma', Status: 'Active' },
      { Title: 'Landscape Irrigation Check', Scope: 'Landscape', Category: 'Weekly', 'Total Items': 14, 'Pass Criteria (%)': 80, Frequency: 'Weekly', 'Custom Scope': '', Owner: 'Raj Patel', Status: 'Active' },
      { Title: 'Civil Structure Crack Inspection', Scope: 'Civil', Category: 'Inspection', 'Total Items': 22, 'Pass Criteria (%)': 95, Frequency: 'Monthly', 'Custom Scope': '', Owner: 'John Smith', Status: 'Active' },
      { Title: 'Security Perimeter Patrol Checklist', Scope: 'Security', Category: 'Daily', 'Total Items': 28, 'Pass Criteria (%)': 100, Frequency: 'Daily', 'Custom Scope': '', Owner: 'Omar Saeed', Status: 'Active' },
      { Title: 'Fire Pump Weekly Test', Scope: 'Fire Protection', Category: 'Weekly', 'Total Items': 16, 'Pass Criteria (%)': 100, Frequency: 'Weekly', 'Custom Scope': '', Owner: 'Ahmed Ali', Status: 'Active' },
      { Title: 'Custom Scope Example — Data Center Tier III', Scope: 'General', Category: 'Handover', 'Total Items': 45, 'Pass Criteria (%)': 100, Frequency: 'Per Job', 'Custom Scope': 'Data Center Tier III', Owner: 'Mohammed Hassan', Status: 'Draft' },
    ],
  },
  {
    code: 'locations',
    name: 'Location Master',
    icon: 'fa-location-dot',
    category: 'assets',
    color: '#8B5CF6',
    description: 'Master location hierarchy: site → project → building → floor → area → room → space',
    columns: [
      C('Location Code', 'auto_increment', 100),
      C('Site', 'dropdown', 100, ['Main Site', 'North Campus', 'South Campus', 'Offsite']),
      C('Project', 'text', 120),
      C('Building', 'building', 120),
      C('Floor', 'text', 80),
      C('Area', 'text', 100),
      C('Room', 'text', 90),
      C('Space Code', 'text', 90),
      C('Space Type', 'dropdown', 110, ['Office', 'Plant Room', 'Storage', 'Common Area', 'Restroom', 'Kitchen', 'Meeting Room', 'Server Room', 'Corridor', 'Other']),
      C('Area (sqm)', 'number', 90),
      C('Occupancy', 'dropdown', 90, ['Single Tenant', 'Shared', 'Unoccupied', 'Maintenance']),
      C('Status', 'status', 90, ['Active', 'Inactive', 'Under Maintenance']),
    ],
    records: [
      { Site: 'Main Site', Project: 'Tower A', Building: 'Building A', Floor: 'B1', Area: 'Plant Room', Room: 'PR-A-01', 'Space Code': 'A-B1-PR01', 'Space Type': 'Plant Room', 'Area (sqm)': 220, Occupancy: 'Single Tenant', Status: 'Active' },
      { Site: 'Main Site', Project: 'Tower A', Building: 'Building A', Floor: 'G', Area: 'Lobby', Room: 'LBY-01', 'Space Code': 'A-G-LBY1', 'Space Type': 'Common Area', 'Area (sqm)': 380, Occupancy: 'Shared', Status: 'Active' },
      { Site: 'Main Site', Project: 'Tower A', Building: 'Building A', Floor: '3', Area: 'Office', Room: 'OFF-301', 'Space Code': 'A-3-0301', 'Space Type': 'Office', 'Area (sqm)': 45, Occupancy: 'Single Tenant', Status: 'Active' },
      { Site: 'North Campus', Project: 'Warehouse', Building: 'Building C', Floor: 'G', Area: 'Storage', Room: 'WH-01', 'Space Code': 'C-G-WH01', 'Space Type': 'Storage', 'Area (sqm)': 1200, Occupancy: 'Unoccupied', Status: 'Under Maintenance' },
      { Site: 'South Campus', Project: 'Utilities', Building: 'Building B', Floor: 'B2', Area: 'Server Room', Room: 'SRV-01', 'Space Code': 'B-B2-SRV1', 'Space Type': 'Server Room', 'Area (sqm)': 80, Occupancy: 'Single Tenant', Status: 'Active' },
    ],
  },
  {
    code: 'wo_attachments',
    name: 'WO Attachments & Stages',
    icon: 'fa-paperclip',
    category: 'maintenance',
    color: '#F59E0B',
    description: 'Attachments and stage-by-stage documentation for work orders',
    columns: [
      C('Attachment ID', 'auto_increment', 90),
      C('WO Number', 'text', 100),
      C('Stage', 'dropdown', 110, ['Open', 'Assigned', 'In Progress', 'On Hold', 'Completion', 'Closed']),
      C('Attachment Type', 'dropdown', 120, ['Photo', 'Document', 'Report', 'Signature', 'Invoice', 'Other']),
      C('File', 'image', 120),
      C('Document URL', 'url', 140),
      C('Notes', 'long_text', 180),
      C('Uploaded By', 'employee', 120),
      C('Uploaded At', 'datetime', 130),
      C('Stage Timestamp', 'datetime', 130),
    ],
    records: [
      { 'WO Number': 'WO-0001', Stage: 'In Progress', 'Attachment Type': 'Photo', File: '', 'Document URL': '', Notes: 'Photo of bearing damage before replacement', 'Uploaded By': 'Mohammed Hassan', 'Uploaded At': '2025-02-10T10:30', 'Stage Timestamp': '2025-02-10T10:30' },
      { 'WO Number': 'WO-0001', Stage: 'Completion', 'Attachment Type': 'Photo', File: '', 'Document URL': '', Notes: 'After replacement — new bearing installed and aligned', 'Uploaded By': 'Mohammed Hassan', 'Uploaded At': '2025-02-12T15:00', 'Stage Timestamp': '2025-02-12T15:00' },
      { 'WO Number': 'WO-0003', Stage: 'Closed', 'Attachment Type': 'Signature', File: '', 'Document URL': '', Notes: 'Customer sign-off on completion', 'Uploaded By': 'Priya Sharma', 'Uploaded At': '2025-02-09T09:00', 'Stage Timestamp': '2025-02-09T09:00' },
      { 'WO Number': 'WO-0001', Stage: 'Assigned', 'Attachment Type': 'Document', File: '', 'Document URL': '', Notes: 'Work assignment letter with safety briefing', 'Uploaded By': 'John Smith', 'Uploaded At': '2025-02-10T08:15', 'Stage Timestamp': '2025-02-10T08:00' },
    ],
  },
];

// Master data helpers — these feed dropdown/employee/vendor lookups
export const EMPLOYEES = [
  'Ahmed Ali', 'Sara Khan', 'Mohammed Hassan', 'Fatima Al-Rashid',
  'John Smith', 'Priya Sharma', 'Raj Patel', 'Omar Saeed',
];

export const DEPARTMENTS = [
  'Operations', 'Maintenance', 'Safety', 'Administration',
  'HR', 'Finance', 'IT', 'Procurement', 'Security',
];

export const BUILDINGS = ['Building A', 'Building B', 'Building C'];

export const ASSETS = ['AHU-01', 'Elevator-03', 'Pump-05', 'Chiller CH-01', 'Generator GEN-02'];

export const EQUIPMENT = [
  'Chiller CH-01', 'AHU-03', 'Generator GEN-02', 'Pump-05', 'FCU-12',
  'BMS Panel-01', 'Pressure Gauge PG-01', 'Multimeter FL-03', 'Thermocouple TC-07',
];

export const VENDORS = [
  'CoolTech Services LLC', 'GuardForce International', 'Al-Fanar Electrical Co.',
  'Schindler Middle East', 'Gulf Steel Fabrication',
];

export const MASTER_DATA: Record<string, string[]> = {
  employee: EMPLOYEES,
  department: DEPARTMENTS,
  building: BUILDINGS,
  asset: ASSETS,
  equipment: EQUIPMENT,
  vendor: VENDORS,
};
